services:
    cloudflared:
        image: cloudflare/cloudflared:latest
        container_name: cloudflared
        restart: unless-stopped
        networks:
            - cloudflare
        command: tunnel run --token ${CLOUDFLARE_TOKEN}

networks:
    cloudflare:
        external: true
